version: 1.0.{build}
os:
  - Visual Studio 2015
clone_depth: 1
environment:
  matrix:
    - TOOLCHAIN_VERSION: 14.0
      RUST: nightly
      PYTHON: "C:\\Python27"
      platform: Win32
    - TOOLCHAIN_VERSION: 14.0
      RUST: nightly
      PYTHON: "C:\\Python27-x64"
      platform: x64

artifacts:
  - path: dist\*
    name: wheel

build_script: appveyor.bat
skip_branch_with_pr: true
deploy:
  name: mbed-os-s3
  provider: S3
  region: eu-west-1
  access_key_id: AKIAJRSWHGVBJUV5HFZA
  secret_access_key:
    secure: Oeg8mQ7lfWYLBZ4Qx2saBO+I2/Oe1rPx4JFeB6JWdz/reCQ/RHWij6YZ5LWe8qen
  bucket: mbed-os
  folder: builds/cmsis-pack-manager/
  artifact: wheel
  set_public: true
  on:
    branch: master